const List<Map<String, dynamic>> EnProductType = [
  {'name': 'Goods', 'id': 1},
  {'name': 'Service', 'id': 2}
];

const List<Map<String, dynamic>> enStateCode = [
  {'text': 'Jammu Kashmir (1)', 'id': 1},
  {'text': 'Himachal Pradesh (2)', 'id': 2},
  {'text': 'Punjab (3)', 'id': 3},
  {'text': 'Chandigarh (4)', 'id': 4},
  {'text': 'Uttarakhand (5)', 'id': 5},
  {'text': 'Haryana (6)', 'id': 6},
  {'text': 'Delhi (7)', 'id': 7},
  {'text': 'Rajasthan (8)', 'id': 8},
  {'text': 'Uttar Pradesh (9)', 'id': 9},
  {'text': 'Bihar (10)', 'id': 10},
  {'text': 'Sikkim (11)', 'id': 11},
  {'text': 'Arunachal Pradesh (12)', 'id': 12},
  {'text': 'Nagaland (13)', 'id': 13},
  {'text': 'Manipur (14)', 'id': 14},
  {'text': 'Mizoram (15)', 'id': 15},
  {'text': 'Tripura (16)', 'id': 16},
  {'text': 'Meghalaya (17)', 'id': 17},
  {'text': 'Assam (18)', 'id': 18},
  {'text': 'West Bengal (19)', 'id': 19},
  {'text': 'Jharkhand (20)', 'id': 20},
  {'text': 'Orissa (21)', 'id': 21},
  {'text': 'Chhattisgarh (22)', 'id': 22},
  {'text': 'Madhya Pradesh (23)', 'id': 23},
  {'text': 'Gujarat (24)', 'id': 24},
  {'text': 'Daman And Diu (25)', 'id': 25},
  {'text': 'Dadra And Nagar Haveli (26)', 'id': 26},
  {'text': 'Maharashtra (27)', 'id': 27},
  {'text': 'Andhra Pradesh Old (28)', 'id': 28},
  {'text': 'Karnataka (29)', 'id': 29},
  {'text': 'Goa (30)', 'id': 30},
  {'text': 'Lakshadweep (31)', 'id': 31},
  {'text': 'Kerala (32)', 'id': 32},
  {'text': 'Tamil Nadu (33)', 'id': 33},
  {'text': 'Puducherry (34)', 'id': 34},
  {'text': 'Andaman And Nicobar Islands (35)', 'id': 35},
  {'text': 'Telangana (36)', 'id': 36},
  {'text': 'Andhra Pradesh New (37)', 'id': 37},
];

const List<Map<String, dynamic>> itemUsedForTypeForItemDropdown = [
  {'text': 'Trading', 'id': 1},
  {'text': 'Finish Goods', 'id': 2},
  {'text': 'Raw Material', 'id': 3},
  {'text': 'Semi Finish Goods', 'id': 4},
  {'text': 'Packing Material', 'id': 5},
  {'text': 'Capital Goods', 'id': 6},
  {'text': 'Scrap Items', 'id': 7},
  {'text': 'Operations', 'id': 8},
  {'text': 'TASK', 'id': 9},
  {'text': 'Labour', 'id': 10},
  {'text': 'Assembly', 'id': 11},
  {'text': 'VBELT', 'id': 12},
  {'text': 'MQC', 'id': 13},
  {'text': 'Service', 'id': 14},
  {'text': 'Electrical', 'id': 15},
  {'text': 'Electronics', 'id': 16},
  {'text': 'Mechanical', 'id': 17},
  {'text': 'Consumable', 'id': 18},
  {'text': 'Customer Property', 'id': 19},
  {'text': 'Fixed Asset', 'id': 20},
  {'text': 'Software', 'id': 21},
  {'text': 'Vision', 'id': 22},
  {'text': 'Lubricant', 'id': 23},
  {'text': 'Lab', 'id': 24},
  {'text': 'Extra Charge', 'id': 25},
  {'text': 'Activity', 'id': 26},
];
